/**
 * A marker unique enough that it never collides with a hand-written hook,
 * used both inside the generated script (so a health-check can recognise
 * "this file is ours") and to decide whether an existing pre-commit hook is
 * foreign (installed by something else) before ever overwriting it.
 */
export const HOOK_MARKER = "not-submodules-pre-commit-hook";

/**
 * The self-maintaining pre-commit hook, written to `.git/hooks/pre-commit`
 * at install time. Plain POSIX `/bin/sh` (Q29) - no bash-isms - because this
 * runs standalone, outside Obsidian, on whatever shell git invokes it with.
 *
 * Deliberately self-contained (Q25): it re-implements the same
 * directory-vs-file `.git` classification `scan.ts` uses, independently, in
 * shell, rather than reading anything the plugin wrote - a commit can happen
 * with Obsidian closed. Any change to one classification implementation
 * must be mirrored in the other (documented risk, not a bug).
 *
 * On every commit it: (1) walks the repo for nested `.git` entries,
 * classifying original/worktree/submodule; (2) drops any candidate without a
 * resolvable `origin` (Q-matches scan.ts's "not yet trackable" rule); (3)
 * fully regenerates a managed, marker-delimited block in `.gitignore` from
 * scratch - one path-anchored, directory-anchored line per location (Q26);
 * (4) untracks from the index anything newly ignored that was still tracked
 * (Q31); (5) stages `.gitignore`; (6) never blocks the commit - any internal
 * failure is warned to stderr and the hook still exits 0 (Q29).
 */
export const PRE_COMMIT_HOOK_SCRIPT = `#!/bin/sh
# Generated by the not-submodules Obsidian plugin - do not edit by hand.
# Re-run "Install git hook" in the plugin's settings to regenerate this file.
# ${HOOK_MARKER}

nsm_main() {
	set -e

	nsm_root=$(git rev-parse --show-toplevel)
	cd "$nsm_root"

	nsm_gitmodules_paths=""
	if [ -f "$nsm_root/.gitmodules" ]; then
		nsm_gitmodules_paths=$(sed -n 's/^[[:space:]]*path[[:space:]]*=[[:space:]]*//p' "$nsm_root/.gitmodules")
	fi

	nsm_raw=$(mktemp)
	nsm_list=$(mktemp)
	trap 'rm -f "$nsm_raw" "$nsm_list"' EXIT

	find "$nsm_root" -name .git -print -prune -o \\
		\\( -name node_modules -o -name .trash -o -name .space -o -name _to_delete -o -name .DS_Store \\) -prune \\
		> "$nsm_raw" 2>/dev/null

	while IFS= read -r nsm_git_path; do
		[ "$nsm_git_path" = "$nsm_root/.git" ] && continue

		nsm_loc=\${nsm_git_path%/.git}
		nsm_rel=\${nsm_loc#"$nsm_root/"}

		nsm_kind=""
		if printf '%s\\n' "$nsm_gitmodules_paths" | grep -Fqx "$nsm_rel"; then
			nsm_kind="submodule"
		elif [ -d "$nsm_git_path" ]; then
			nsm_kind="original"
		elif [ -f "$nsm_git_path" ]; then
			nsm_target=$(sed -n 's/^gitdir:[[:space:]]*//p' "$nsm_git_path" | head -n1)
			case "$nsm_target" in
				*.git/worktrees/*) nsm_kind="worktree" ;;
				*.git/modules/*) nsm_kind="submodule" ;;
				*) nsm_kind="" ;;
			esac
		fi

		[ "$nsm_kind" = "submodule" ] && continue
		[ -z "$nsm_kind" ] && continue

		nsm_origin=$(git -C "$nsm_loc" remote get-url origin 2>/dev/null) || nsm_origin=""
		[ -z "$nsm_origin" ] && continue

		printf '%s\\n' "$nsm_rel" >> "$nsm_list"
	done < "$nsm_raw"

	nsm_gitignore="$nsm_root/.gitignore"
	nsm_new=$(mktemp)

	if [ -f "$nsm_gitignore" ]; then
		awk '
			/^# >>> not-submodules: nested repos \\(auto-generated/ { skip=1; next }
			/^# <<< not-submodules: nested repos <<</ { skip=0; next }
			skip { next }
			{ print }
		' "$nsm_gitignore" > "$nsm_new"
	fi

	if [ -s "$nsm_list" ]; then
		printf '# >>> not-submodules: nested repos (auto-generated by the not-submodules plugin - do not edit by hand) >>>\\n' >> "$nsm_new"
		sort -u "$nsm_list" >> "$nsm_new.sorted"
		while IFS= read -r nsm_rel_line; do
			printf '/%s/\\n' "$nsm_rel_line" >> "$nsm_new"
		done < "$nsm_new.sorted"
		rm -f "$nsm_new.sorted"
		printf '# <<< not-submodules: nested repos <<<\\n' >> "$nsm_new"
	fi

	mv "$nsm_new" "$nsm_gitignore"

	if [ -s "$nsm_list" ]; then
		while IFS= read -r nsm_rel_line; do
			git rm -r --cached --ignore-unmatch -- "$nsm_rel_line" >/dev/null 2>&1 || true
		done < "$nsm_list"
	fi

	git add -- "$nsm_gitignore"
}

( nsm_main )
nsm_status=$?
if [ "$nsm_status" -ne 0 ]; then
	echo "not-submodules: pre-commit hook failed internally - skipping this run (commit not blocked)" >&2
fi

exit 0
`;
